name: Setup
description: Environment setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: pnpm

    - shell: bash
      run: |
        pnpm install --frozen-lockfile
